//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickDataTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Overwatch\\")]
        public string Path_CurrentOW {
            get {
                return ((string)(this["Path_CurrentOW"]));
            }
            set {
                this["Path_CurrentOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> List_OWInsts {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["List_OWInsts"]));
            }
            set {
                this["List_OWInsts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\")]
        public string Path_Output {
            get {
                return ((string)(this["Path_Output"]));
            }
            set {
                this["Path_Output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TAB_LIST_ModeIndex {
            get {
                return ((int)(this["TAB_LIST_ModeIndex"]));
            }
            set {
                this["TAB_LIST_ModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TAB_LIST_OutputJSON {
            get {
                return ((bool)(this["TAB_LIST_OutputJSON"]));
            }
            set {
                this["TAB_LIST_OutputJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TAB3_ModeIndex {
            get {
                return ((int)(this["TAB3_ModeIndex"]));
            }
            set {
                this["TAB3_ModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TAB3_FormatIndex {
            get {
                return ((int)(this["TAB3_FormatIndex"]));
            }
            set {
                this["TAB3_FormatIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TAB3_LosslessTexture {
            get {
                return ((bool)(this["TAB3_LosslessTexture"]));
            }
            set {
                this["TAB3_LosslessTexture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TAB3_LOD {
            get {
                return ((int)(this["TAB3_LOD"]));
            }
            set {
                this["TAB3_LOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TAB3_NoExtract {
            get {
                return ((string)(this["TAB3_NoExtract"]));
            }
            set {
                this["TAB3_NoExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TAB3_NoConvert {
            get {
                return ((string)(this["TAB3_NoConvert"]));
            }
            set {
                this["TAB3_NoConvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TAB3_NoEnvExtract {
            get {
                return ((string)(this["TAB3_NoEnvExtract"]));
            }
            set {
                this["TAB3_NoEnvExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\")]
        public string TAB_SETTINGS_OutputPath {
            get {
                return ((string)(this["TAB_SETTINGS_OutputPath"]));
            }
            set {
                this["TAB_SETTINGS_OutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TAB_SETTINGS_LangIndex {
            get {
                return ((int)(this["TAB_SETTINGS_LangIndex"]));
            }
            set {
                this["TAB_SETTINGS_LangIndex"] = value;
            }
        }
    }
}
